### ISSUE TITLE
infografia Evelyn

### ISSUE THREAD

**Issue by evelyn-santiago** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-evelyn-santiago#1]
[Infografía_ Evelyn.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-evelyn-santiago/files/14727716/Infografia_.Evelyn.pdf)

**Comment by MarcoRg06** [comment]
Con respecto a la rúbrica de evaluación obtuviste un 18%
Porque:
-Una infografía no lleva mucha información.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
